USE [master]
GO

/****** Object:  Database [DebtManagement]    Script Date: 11/21/2024 4:43:44 AM ******/
CREATE DATABASE [DebtManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DebtManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DebtManagement.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DebtManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DebtManagement_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DebtManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DebtManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DebtManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DebtManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DebtManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DebtManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [DebtManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DebtManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DebtManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DebtManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DebtManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DebtManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DebtManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DebtManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DebtManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DebtManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DebtManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DebtManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DebtManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DebtManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DebtManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DebtManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DebtManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DebtManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [DebtManagement] SET  MULTI_USER 
GO

ALTER DATABASE [DebtManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DebtManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DebtManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DebtManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DebtManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DebtManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DebtManagement] SET QUERY_STORE = ON
GO

ALTER DATABASE [DebtManagement] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DebtManagement] SET  READ_WRITE 
GO


